Training-FPT0/Controllers/TraineeCoursesController.cs
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Training_FPT0.Models;
using System.Data.Entity;
using Training_FPT0.ViewModels;

namespace Training_FPT0.Controllers
{
    public class TraineeCoursesController : Controller
    {

		private ApplicationDbContext _context;
		public TraineeCoursesController()
		{
			_context = new ApplicationDbContext();
		}

		[HttpGet]
		// GET: TraineeToCourses
		public ActionResult Index(string searchTrainee)
		{
			var traineecourses = _context.TraineeCourses
								   .Include(tr => tr.Course)
								   .Include(tr => tr.Trainee);

			if (!String.IsNullOrEmpty(searchTrainee))
			{
				traineecourses = traineecourses.Where(
						s => s.Trainee.UserName.Contains(searchTrainee) ||
						s.Trainee.Email.Contains(searchTrainee));
			}

			return View(traineecourses);
		}

		[HttpGet]
		public ActionResult Create()
		{
			var viewModel = new TraineeCourseViewModel
			{
				Courses = _context.Courses.ToList(),
				Trainees = _context.Users.ToList()
			};

			return View(viewModel);
		}


		[HttpPost]
		public ActionResult Create(TraineeCourse traineeCourse)
		{
			var newTraineeCourse = new TraineeCourse
			{
				TraineeId = traineeCourse.TraineeId,
				CourseId = traineeCourse.CourseId
			};

			_context.TraineeCourses.Add(newTraineeCourse);
			_context.SaveChanges();
			return RedirectToAction("Index");
		}

		[HttpGet]
		public ActionResult Delete(int id)
		{
			var traineeInDb = _context.TraineeCourses.SingleOrDefault(traineeindb => traineeindb.Id == id);
			if (traineeInDb == null)
			{
				return HttpNotFound();
			}

			_context.TraineeCourses.Remove(traineeInDb);
			_context.SaveChanges();
			return RedirectToAction("Index");
		}

		[HttpGet]
		public ActionResult Edit(int id)
		{
			var traineeInDb = _context.TraineeCourses.SingleOrDefault(traineeindb => traineeindb.Id == id);

			if (traineeInDb == null)
			{
				return HttpNotFound();
			}

			var viewModel = new TraineeCourseViewModel
			{
				TraineeCourse = traineeInDb,
				Courses = _context.Courses.ToList(),
			};

			return View(viewModel);
		}

		[HttpPost]
		public ActionResult Edit(TraineeCourse traineeCourse)
		{
			var traineeInDb = _context.TraineeCourses.SingleOrDefault(traineeindb => traineeindb.Id == traineeCourse.Id);

			if (traineeInDb == null)
			{
				return HttpNotFound();
			}

			traineeInDb.CourseId = traineeCourse.CourseId;

			_context.SaveChanges();
			return RedirectToAction("Index");
		}
	}
}

Training-FPT0/Views/TraineeCourses/Create.cshtml
@model Training_FPT0.ViewModels.TraineeCourseViewModel

@{ ViewBag.Title = "Create"; }

<h2>Assign Trainee to Course</h2>

@using (Html.BeginForm("Create", "TraineeCourses", FormMethod.Post))
{
    <div class="form-group">
        @Html.LabelFor(tr => tr.TraineeCourse.TraineeId)
        @Html.DropDownListFor(tr => tr.TraineeCourse.TraineeId
          , new SelectList(Model.Trainees, "Id", "Email"),
          "Select Trainee",
          new { @class = "form-control" }
        )
    </div>

    <div class="form-group">
        @Html.LabelFor(tr => tr.TraineeCourse.Course.Name)
        @Html.DropDownListFor(tr => tr.TraineeCourse.CourseId
          , new SelectList(Model.Courses, "Id", "Name"),
          "Select Course",
          new { @class = "form-control" }
        )
    </div>

    <button type="submit" class="btn btn-primary">Assign</button>
}

Training-FPT0/Views/TraineeCourses/Edit.cshtml
@model Training_FPT0.ViewModels.TraineeCourseViewModel
@{ ViewBag.Title = "Edit"; }

<h2>Edit</h2>
@Html.ValidationSummary(false, "", new { @class = "text-danger" })

@using (Html.BeginForm("Edit", "TraineeCourses", FormMethod.Post))
{
    <div class="form-group">
        @Html.LabelFor(tr => tr.TraineeCourse.Course.Name)
        @Html.DropDownListFor(tr => tr.TraineeCourse.CourseId
           , new SelectList(Model.Courses, "Id", "Name"),
           "Select Course",
           new { @class = "form-control" })
    </div>
    <button type="submit" class="btn btn-primary">Edit</button>
}


<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Training-FPT0/Views/TraineeCourses/Index.cshtml
@model IEnumerable<Training_FPT0.Models.TraineeCourse>

@{ ViewBag.Title = "Assign Trainee to Course"; }

<h2>Manage Trainee</h2>

@using (Html.BeginForm("Index", "TraineeCourses", FormMethod.Get))
{
    <p>
        <input type="search" placeholder="Enter Trainee Email or UserName"
               name="searchTrainee" style="width:225px; height:33px;" />

        <input type="submit" value="Search" class="btn btn-primary" />

        @Html.ActionLink("View all Trainee", "Index", "TraineeCourses")
    </p>
}

@if (Request.IsAuthenticated && User.IsInRole("TrainingStaff"))
{
    @Html.ActionLink("Assign Trainee to Course", "Create")
}

<table class="table table-striped">
    <tr>
        <th>Id</th>
        <th>Trainee Email</th>
        <th>Trainee UserName</th>
        <th>Course Name</th>
        @if (Request.IsAuthenticated && User.IsInRole("TrainingStaff"))
        {
            <th>Edit</th>
            <th>Delete</th>
        }

    </tr>
    @foreach (var trainee in Model)
    {
        <tr>
            <th>@trainee.Id</th>
            <th>@trainee.Trainee.Email</th>
            <th>@trainee.Trainee.UserName</th>
            <th>@trainee.Course.Name</th>
            @if (Request.IsAuthenticated && User.IsInRole("TrainingStaff"))
            {
                <th>@Html.ActionLink("Edit", "Edit", new { id = trainee.Id })</th>
                <th>@Html.ActionLink("Delete", "Delete", new { id = trainee.Id })</th>
            }
        </tr>
    }
</table>
@Html.ActionLink("Back to home", "Index", "Home")