Training-FPT0/Models/TrainerTopic.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Training_FPT0.Models
{
    public class TrainerTopic
    {
        public int Id { get; set; }
        public string TrainerId { get; set; }
        public int TopicId { get; set; }

        public ApplicationUser Trainer { get; set; }
        public Topic Topic { get; set; }

    }
}

Training-FPT0/ViewModels/TrainerTopicViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using Training_FPT0.Models;

namespace Training_FPT0.ViewModels
{
    public class TrainerTopicViewModel
    {
        public TrainerTopic TrainerTopic { get; set; }
        public IEnumerable<ApplicationUser> Trainers { get; set; }
        public IEnumerable<Topic> Topics { get; set; }

    }
}

Training-FPT0/Controllers/TrainerTopicsController.cs
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Training_FPT0.Models;
using Training_FPT0.ViewModels;
using System.Data.Entity;
using System.Data.Entity.Migrations;

namespace Training_FPT0.Controllers
{
    public class TrainerTopicsController : Controller
    {
		private ApplicationDbContext _context;

		public TrainerTopicsController()
		{
			_context = new ApplicationDbContext();
		}

		[HttpGet]
		// GET: TraineeToCourses
		public ActionResult Index(string searchTrainer)
		{
			var trainertopics = _context.TrainerTopics
								   .Include(tr => tr.Topic)
								   .Include(tr => tr.Trainer);

			if (!String.IsNullOrEmpty(searchTrainer))
			{
				trainertopics = trainertopics.Where(
						s => s.Trainer.UserName.Contains(searchTrainer) ||
						s.Trainer.Email.Contains(searchTrainer));
			}

			return View(trainertopics);
		}

		[HttpGet]
		public ActionResult Create()
		{
			var viewModel = new TrainerTopicViewModel
			{
				Topics = _context.Topics.ToList(),
				Trainers = _context.Users.ToList()
			};

			return View(viewModel);
		}


		[HttpPost]
		public ActionResult Create(TrainerTopic trainerTopic)
		{
			var newTrainerTopic = new TrainerTopic
			{
				TrainerId = trainerTopic.TrainerId,
				TopicId = trainerTopic.TopicId
			};

			_context.TrainerTopics.Add(newTrainerTopic);
			_context.SaveChanges();
			return RedirectToAction("Index");
		}

		[HttpGet]
		public ActionResult Delete(int id)
		{
			var trainerInDb = _context.TrainerTopics.SingleOrDefault(trainerinDb => trainerinDb.Id == id);
			if (trainerInDb == null)
			{
				return HttpNotFound();
			}

			_context.TrainerTopics.Remove(trainerInDb);
			_context.SaveChanges();
			return RedirectToAction("Index");
		}

		[HttpGet]
		public ActionResult Edit(int id)
		{
			var trainerInDb = _context.TrainerTopics.SingleOrDefault(trainerinDb => trainerinDb.Id == id);

			if (trainerInDb == null)
			{
				return HttpNotFound();
			}

			var viewModel = new TrainerTopicViewModel
			{
				TrainerTopic = trainerInDb,
				Topics = _context.Topics.ToList(),
			};

			return View(viewModel);
		}

		[HttpPost]
		public ActionResult Edit(TrainerTopic trainerTopic)
		{
			var trainerInDb = _context.TrainerTopics.SingleOrDefault(trainerinDb => trainerinDb.Id == trainerTopic.Id);

			if (trainerInDb == null)
			{
				return HttpNotFound();
			}

			trainerInDb.TopicId = trainerTopic.TopicId;

			_context.SaveChanges();
			return RedirectToAction("Index");
		}
	}
}

Training-FPT0/Views/TrainerTopics/Create.cshtml
@model Training_FPT0.ViewModels.TrainerTopicViewModel

@{ ViewBag.Title = "Create"; }

<h2>Assign Trainer to Topic</h2>

@using (Html.BeginForm("Create", "TrainerTopics", FormMethod.Post))
{
    <div class="form-group">
        @Html.LabelFor(tr => tr.TrainerTopic.TrainerId)
        @Html.DropDownListFor(tr => tr.TrainerTopic.TrainerId
          , new SelectList(Model.Trainers, "Id", "Email"),
          "Select Trainer",
          new { @class = "form-control" }
        )
    </div>

    <div class="form-group">
        @Html.LabelFor(tr => tr.TrainerTopic.Topic.Name)
        @Html.DropDownListFor(tr => tr.TrainerTopic.TopicId
          , new SelectList(Model.Topics, "Id", "Name"),
          "Select Topic",
          new { @class = "form-control" }
        )
    </div>

    <button type="submit" class="btn btn-primary">Assign</button>
}

Training-FPT0/Views/TrainerTopics/Edit.cshtml
@model Training_FPT0.Models.TrainerTopic
@{ ViewBag.Title = "Edit"; }

<h2>Edit</h2>

@Html.ValidationSummary(false, "", new { @class = "text-danger" })
@using (Html.BeginForm("Edit", "TrainerTopics", FormMethod.Post))
{
@Html.HiddenFor(u => u.Id)
                <div class="form-horizontal">
                    <hr />
                    <div class="form-group">
                        @Html.LabelFor(u => u.TrainerId)
                        @Html.EditorFor(u => u.TrainerId, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(u => u.TrainerId, "", new { @class = "text-danger" })
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(u => u.TopicId)
                        @Html.EditorFor(u => u.TopicId, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(u => u.TopicId, "", new { @class = "text-danger" })
                    </div>
                     <div class="form-group">
                        @Html.LabelFor(u => u.CourseId)
                        @Html.EditorFor(u => u.CourseId, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(u => u.CourseId, "", new { @class = "text-danger" })
                    </div>


                    <div class="form-group">
                        <div class="col-md-offset-2 col-md-10">
                            <input type="submit" value="Save" class="btn btn-default" />
                        </div>
                    </div>
                </div>}

<div>
    @Html.ActionLink("Back to List", "UsersWithRoles")
</div>

Training-FPT0/Views/TrainerTopics/Index.cshtml
@model IEnumerable<Training_FPT0.Models.TrainerTopic>

@{ ViewBag.Title = "Manage Trainer Topic"; }

<h2>Manage Trainer</h2>

@using (Html.BeginForm("Index", "TrainerTopics", FormMethod.Get))
{
    <p>
        <input type="search" placeholder="Enter Trainer Email or UserName"
               name="searchTrainer" style="width:225px; height:33px;" />

        <input type="submit" value="Search" class="btn btn-primary" />

        @Html.ActionLink("View all Trainer", "Index", "TrainerTopics")
    </p>
}

@if (Request.IsAuthenticated && User.IsInRole("TrainingStaff"))
{
    @Html.ActionLink("Assign Trainer to Topic", "Create")
}

<table class="table table-striped">
    <tr>
        <th>Id</th>
        <th>Trainer Email</th>
        <th>Trainer UserName</th>
        <th>Topic Name</th>
        @if (Request.IsAuthenticated && User.IsInRole("TrainingStaff"))
        {
            <th>Edit</th>
            <th>Delete</th>
        }

    </tr>
    @foreach (var trainer in Model)
    {
        <tr>
            <th>@trainer.Id</th>
            <th>@trainer.Trainer.Email</th>
            <th>@trainer.Trainer.UserName</th>
            <th>@trainer.Topic.Name</th>
            @if (Request.IsAuthenticated && User.IsInRole("TrainingStaff"))
            {
                <th>@Html.ActionLink("Edit", "Edit", new { id = trainer.Id })</th>
                <th>@Html.ActionLink("Delete", "Delete", new { id = trainer.Id })</th>
            }
        </tr>
    }
</table>
@Html.ActionLink("Back to home", "Index", "Home")